title: Sovereign Cloud Stack

url: https://sovereigncloudstack.github.io
baseurl: /newsletter

headline:
  digest: Community Digest
  journal: Contributor's Journal

description:
  digest: |-
    The latest announcements, information, and events from the SCS community for you at a glance! Together we build tomorrow's federated cloud technology &mdash; putting users and providers in control.
  journal: |-
    Your contributor's journal on open issues, thriving discussions and pendig reviews for you at a glance! Together we build tomorrow's federated cloud technology &mdash; putting users and providers in control.

calltoaction:
    - slug: "beginner"
      title: "Good first issues"
      logo: code-of-conduct
    - slug: "issues"
      title: "Open issues"
      logo: issue-opened
    - slug: "review"
      title: "Review needed"
      logo: code-review
    - slug: "other"
      title: "Other"
      logo: "megaphone"

unsubscribe:
  title: Unsubscribe
  link: https://scs.sovereignit.de/mailman3/postorius/accounts/list-options/scs-member.lists.scs.community/

footer:
  disclaimer: Sovereign Cloud Stack, SCS and the logo are registered trademarks of the Open Source Business Alliance e.V. &mdash; Other trademarks are property of their respective owners.
  imprint:
    title: Imprint
    link: https://scs.community/imprint/
  dataprotection:
    title: Data Protection Statement
    link: https://scs.community/dataprotection/

social:
  - title: Twitter
    icon: /assets/images/twitter.png
    link: https://twitter.com/scs_osballiance
  - title: Mastodon
    icon: /assets/images/mastodon.png
    link: https://fosstodon.org/web/@sovereigncloudstack#
  - title: LinkedIn
    icon: /assets/images/linkedin.png
    link: https://www.linkedin.com/company/sovereigncloudstack
  - title: GitHub
    icon: /assets/images/github.png
    link: https://github.com/SovereignCloudStack
  - title: Matrix
    icon: /assets/images/matrix.png
    link: https://matrix.to/#/!TiDqlLmEUaXqTemaLc:matrix.org?via=matrix.org
  - title: Feed
    icon: /assets/images/rss.png
    link: https://scs.community/feed.xml

style:
  background-color: "#f8f9fa"
  content:
    background-color: "#ffffff"
    color: "#343a40"
  footer:
    background-color: "#7d7d82"
    color: "#ffffff"
  buttons:
    border-radius: 4px
    background-color: "#7d7d82"
    color: "#ffffff"

twitter:
  username: scs_osballiance

author: "Sovereign Cloud Stack"

collections:
  digest:
    output: true
    permalink: /digest/:title/index.html
  journal:
    output: true
    permalink: /journal/:title/index.html

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/default-card.jpg

feed:
  path: ""
  collections:
    digest:
      path: "/digest/feed.xml"
    journal:
      path: "/journal/feed.xml"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-octicons
