title: Sovereign Cloud Stack

unsubscribe:
  title: Unsubscribe
  link: https://scs.sovereignit.de/mailman3/accounts/login/?next=/mailman3/postorius/lists/announce.lists.scs.community/

footer:
  disclaimer: Sovereign Cloud Stack, SCS and the logo are registered trademarks of the Open Source Business Alliance e.V. — Other trademarks are property of their respective owners.
  imprint:
    title: Imprint
    link: https://scs.community/imprint/
  dataprotection:
    title: Data Protection Statement
    link: https://scs.community/dataprotection/
  
social:
  - title: Twitter
    icon: /assets/images/twitter.png
    link: https://twitter.com/scs_osballiance
  - title: LinkedIn
    icon: /assets/images/linkedin.png
    link: https://www.linkedin.com/showcase/sovereigncloudstack
  - title: GitHub
    icon: /assets/images/github.png
    link: https://github.com/SovereignCloudStack
  - title: Matrix
    icon: /assets/images/matrix.png
    link: https://matrix.to/#/!TiDqlLmEUaXqTemaLc:matrix.org?via=matrix.org
  - title: Mailing list
    icon: /assets/images/bullhorn.png
    link: https://scs.sovereignit.de/mailman3/postorius/lists/announce.lists.scs.community/
  - title: Feed
    icon: /assets/images/rss.png
    link: https://scs.community/feed.xml